[package]
name = "discord-rich-presence"
version = "0.1.0"
authors = ["sardonicism-04 <110789901+sardonicism-04@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
windows-named-pipe = "0.1.0"